import { VIPPolicyOutput } from "../vip-policy/vip-policy-types";

export const mockPolicyOutputs: Record<string, VIPPolicyOutput> = {
  MISSING_CONSENT: {
    severity: "HARD_STOP",
    policy_basis: ["CONSENT_MISSING"],
    enforcement_level: "HARD_STOP",
    authority_boundary: "SITE_CAN_ACT",
    actionability: "ACTIONABLE",
    signal_source: "EDC",
    evidence_status: "MISSING",
    ui_actions: ["HARD_STOP_ACTION"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: ["Save"],
    override_policy: {
      override_allowed: false,
      override_roles_allowed: [],
      override_requires_reason: false,
      override_requires_signature: false,
      override_requires_second_reviewer: false,
      override_expires_after_hours: null
    },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "PI",
    escalation_due_within_hours: 0,
    confidence_band: "HIGH",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: "",
    engine_version: "v1",
    reason: "",
    uncertainty_note: ""
  },
  TREND_ONLY: {
    severity: "MEDIUM",
    policy_basis: ["MONITORING_RISK"],
    enforcement_level: "WARNING",
    authority_boundary: "SITE_CAN_ACT",
    actionability: "ACTIONABLE",
    signal_source: "TREND_ENGINE",
    evidence_status: "COMPLETE",
    ui_actions: ["THROTTLE_ALERT"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: [],
    override_policy: {
      override_allowed: true,
      override_roles_allowed: ["CRC"],
      override_requires_reason: false,
      override_requires_signature: false,
      override_requires_second_reviewer: false,
      override_expires_after_hours: null
    },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "CRC",
    escalation_due_within_hours: 72,
    confidence_band: "MEDIUM",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: "",
    engine_version: "v1",
    reason: "",
    uncertainty_note: ""
  },
  PENDING_PI_ADJUDICATION: {
    severity: "CRITICAL",
    policy_basis: ["SUBJECT_SAFETY"],
    enforcement_level: "WARNING",
    authority_boundary: "REQUIRE_PI_REVIEW",
    actionability: "NON_ACTIONABLE_MEDICAL_BOUNDARY",
    signal_source: "LAB_PORTAL",
    evidence_status: "COMPLETE",
    ui_actions: ["REQUIRE_ADJUDICATION"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: [],
    override_policy: {
      override_allowed: false,
      override_roles_allowed: [],
      override_requires_reason: false,
      override_requires_signature: false,
      override_requires_second_reviewer: false,
      override_expires_after_hours: null
    },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "PI",
    escalation_due_within_hours: 24,
    confidence_band: "HIGH",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: "",
    engine_version: "v1",
    reason: "",
    uncertainty_note: ""
  },
  IP_QUARANTINE_BLOCK: {
    severity: "HARD_STOP",
    policy_basis: ["INVESTIGATIONAL_PRODUCT_CONTROL"],
    enforcement_level: "WARNING", // Degraded from hard stop if override allowed
    authority_boundary: "SITE_CAN_ACT",
    actionability: "ACTIONABLE_WITH_HUMAN",
    signal_source: "PHARMACY_LOG",
    evidence_status: "PHYSICAL_RECONCILIATION_REQUIRED",
    ui_actions: ["BLOCK_ACTION"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: [],
    override_policy: {
      override_allowed: true,
      override_roles_allowed: ["PI", "PHARMACIST"],
      override_requires_reason: true,
      override_requires_signature: true,
      override_requires_second_reviewer: true,
      override_expires_after_hours: null
    },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "PI",
    escalation_due_within_hours: 24,
    confidence_band: "HIGH",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: "",
    engine_version: "v1",
    reason: "",
    uncertainty_note: ""
  }
};
