export {
  BLINDING_SCOPES,
  UNBLINDED_PAYLOAD_FIELD_KEYS,
  canViewBlindingScope,
  filterUnblindedRows,
  filterRowsByBlindingScope,
  isUnblindedScopedPayload,
  redactOperationalEventPayload,
  redactOperationalEventPayloadForDisplay,
  redactSubjectUnblindedFields,
  redactUnblindedPayload,
  resolvePayloadBlindingScope,
  type BlindingScope,
  type SubjectUnblindedFields,
} from '@/lib/rbac/blinding'

export {
  canViewUnblindedData,
  canViewUnblindedDataForRole,
} from '@/lib/rbac/unblinded-access'

export {
  anyMembershipHasEffectiveRole,
  membershipHasEffectiveRole,
  normalizeEffectiveRoles,
  resolveEffectiveRoles,
  resolveEffectiveRolesForMembership,
  resolvePrimaryRole,
  type MembershipRoleInput,
} from '@/lib/rbac/effective-roles'

export {
  organizationIdsFromMemberships,
  hasOrganizationMembership,
} from '@/lib/rbac/org-scope'

export {
  EXTERNAL_MONITOR_ROLE,
  EXTERNAL_MONITOR_ROLES,
  EXTERNAL_STUDY_MEMBER_ROLE,
  isExternalActorOrganizationRole,
  isExternalActorStudyRole,
  isExternalMonitorRoleId,
  isSiteInternalOrganizationRole,
  resolveExternalMonitorRoleFromOrganization,
  resolveExternalMonitorRoleFromStudyMember,
  type ExternalMonitorRole,
} from '@/lib/rbac/external-actors'

export {
  CANONICAL_ORGANIZATION_ROLES,
  LEGACY_ORGANIZATION_ROLE,
  ORGANIZATION_ROLES,
  STORED_ORGANIZATION_ROLES,
  isOrganizationAdmin,
  isDataCoordinatorRole,
  isOrganizationOwner,
  isReadOnlyOrganizationRole,
  isStoredOrganizationRole,
  isUnblindedRole,
  normalizeOrganizationRole,
  type OrganizationRole,
  type StoredOrganizationRole,
} from '@/lib/rbac/roles'

export {
  canAccessAdminSection,
  canAccessAdminSectionForRole,
  canAccessCoordinatorWorkspace,
  canAccessCoordinatorWorkspaceForRole,
  canAccessPatientCRM,
  canAccessPatientCRMForRole,
  canManagePatientCRM,
  canManagePatientCRMForRole,
  canAccessBusinessDevelopmentCRM,
  canAccessBusinessDevelopmentCRMForRole,
  canManageBusinessDevelopmentCRM,
  canManageBusinessDevelopmentCRMForRole,
  canAccessCommunications,
  canAccessCommunicationsForRole,
  canManageCommunications,
  canManageCommunicationsForRole,
  canAccessSourceCapture,
  canAccessSourceCaptureForRole,
  canAccessSubjectVisitWorkspace,
  canAccessSubjectVisitWorkspaceForRole,
  canEditClinicalSource,
  canEditClinicalSourceForRole,
  canManageSourceDocuments,
  canManageSourceDocumentsForRole,
  canPrepareSourceDrafts,
  canPrepareSourceDraftsForRole,
  canReviewSourceDocuments,
  canReviewSourceDocumentsForRole,
  canManageStudies,
  canManageStudiesForRole,
  canManageSubjectVisits,
  canManageSubjectVisitsForRole,
  canManageTemplates,
  canManageTemplatesForRole,
  canManageUnblindedData,
  canManageUnblindedDataForRole,
  canManageUsers,
  canManageUsersForRole,
  canMonitorUnblindedData,
  canMonitorUnblindedDataForRole,
  canMutateOrganizationData,
  canMutateOrganizationDataForRole,
  canPerformOwnershipCriticalActions,
  canPerformOwnershipCriticalActionsForRole,
  canSignClinicalSource,
  canSignClinicalSourceForRole,
  canViewReports,
  canViewReportsForRole,
  canViewFinancialData,
  canViewFinancialDataForRole,
  canViewVpi,
  canViewVpiForRole,
  hasSiteAdminAccess,
  membershipsWithSiteAdminAccess,
  resolveSitePermissions,
  siteAdminOrganizationSummaries,
  type SitePermissionSnapshot,
} from '@/lib/rbac/permissions'
