import ExcelJS from 'exceljs'
import { CRAMonitoringWorkbookEvidence } from '../types'

export async function renderCRAMonitoringWorkbook(evidence: CRAMonitoringWorkbookEvidence): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = evidence.generatedBy
  workbook.lastModifiedBy = evidence.generatedBy
  workbook.created = new Date()
  workbook.modified = new Date()

  // Helper to safely format nulls as '-'
  const safeStr = (val: unknown) => (val === null || val === undefined || val === '') ? '-' : String(val)

  // 1. Cover Sheet
  const coverSheet = workbook.addWorksheet('Cover')
  coverSheet.columns = [
    { header: 'Property', key: 'property', width: 30 },
    { header: 'Value', key: 'value', width: 50 },
  ]
  coverSheet.getRow(1).font = { bold: true }
  
  coverSheet.addRows([
    { property: 'Workbook Name', value: evidence.workbookName },
    { property: 'Study Name', value: evidence.studyName },
    { property: 'Protocol Number', value: safeStr(evidence.protocolNumber) },
    { property: 'Site', value: evidence.site },
    { property: 'Generated At', value: evidence.generatedAt },
    { property: 'Generated By', value: evidence.generatedBy },
    { property: 'As Of Date', value: evidence.asOfDate },
    { property: 'Audience', value: evidence.audience },
    { property: 'Scope Summary', value: evidence.scopeSummary },
    { property: 'Subject Count', value: evidence.subjectCount },
    { property: 'Visit Count', value: evidence.visitCount },
    { property: 'Version Logic', value: evidence.versionLogic },
    { property: 'Deliverable Run ID', value: evidence.deliverableRunId },
  ])

  // 2. Subject Index
  const subjectSheet = workbook.addWorksheet('Subject Index')
  subjectSheet.columns = [
    { header: 'Subject Identifier', key: 'subjectIdentifier', width: 20 },
    { header: 'Subject Status', key: 'subjectStatus', width: 20 },
    { header: 'Enrollment Date', key: 'enrollmentDate', width: 20 },
    { header: 'Screening Status', key: 'screeningStatus', width: 20 },
    { header: 'Randomization Status', key: 'randomizationStatus', width: 20 },
    { header: 'Current Consent Status', key: 'currentConsentStatus', width: 25 },
    { header: 'Current Consent Version', key: 'currentConsentVersion', width: 25 },
    { header: 'Latest Visit Status', key: 'latestVisitStatus', width: 25 },
    { header: 'Notes', key: 'notes', width: 30 },
  ]
  subjectSheet.getRow(1).font = { bold: true }
  subjectSheet.views = [{ state: 'frozen', xSplit: 1, ySplit: 1 }]
  
  evidence.subjects.forEach(s => {
    subjectSheet.addRow({
      subjectIdentifier: safeStr(s.subjectIdentifier),
      subjectStatus: safeStr(s.subjectStatus),
      enrollmentDate: safeStr(s.enrollmentDate),
      screeningStatus: safeStr(s.screeningStatus),
      randomizationStatus: safeStr(s.randomizationStatus),
      currentConsentStatus: safeStr(s.currentConsentStatus),
      currentConsentVersion: safeStr(s.currentConsentVersion),
      latestVisitStatus: safeStr(s.latestVisitStatus),
      notes: safeStr(s.notes),
    })
  })

  // 3. Visit Index
  const visitSheet = workbook.addWorksheet('Visit Index')
  visitSheet.columns = [
    { header: 'Subject Identifier', key: 'subjectIdentifier', width: 20 },
    { header: 'Visit Name', key: 'visitName', width: 25 },
    { header: 'Visit Date', key: 'visitDate', width: 20 },
    { header: 'Visit Status', key: 'visitStatus', width: 20 },
    { header: 'Source Version Used', key: 'sourceVersionUsed', width: 25 },
    { header: 'Source Package ID', key: 'sourcePackageId', width: 35 },
    { header: 'Procedures Completed', key: 'proceduresCompletedCount', width: 25 },
    { header: 'Procedures Expected', key: 'proceduresExpectedCount', width: 25 },
    { header: 'Signature Status', key: 'signatureStatus', width: 20 },
  ]
  visitSheet.getRow(1).font = { bold: true }
  visitSheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }]
  
  evidence.visits.forEach(v => {
    visitSheet.addRow({
      subjectIdentifier: safeStr(v.subjectIdentifier),
      visitName: safeStr(v.visitName),
      visitDate: safeStr(v.visitDate),
      visitStatus: safeStr(v.visitStatus),
      sourceVersionUsed: safeStr(v.sourceVersionUsed),
      sourcePackageId: safeStr(v.sourcePackageId),
      proceduresCompletedCount: safeStr(v.proceduresCompletedCount),
      proceduresExpectedCount: safeStr(v.proceduresExpectedCount),
      signatureStatus: safeStr(v.signatureStatus),
    })
  })

  // 4. Procedure Matrix
  const procSheet = workbook.addWorksheet('Procedure Matrix')
  procSheet.columns = [
    { header: 'Subject Identifier', key: 'subjectIdentifier', width: 20 },
    { header: 'Visit Name', key: 'visitName', width: 25 },
    { header: 'Visit Date', key: 'visitDate', width: 20 },
    { header: 'Procedure Name', key: 'procedureName', width: 30 },
    { header: 'Procedure Status', key: 'procedureStatus', width: 20 },
    { header: 'Performed Date', key: 'performedDate', width: 20 },
    { header: 'Performed By', key: 'performedBy', width: 25 },
    { header: 'Source Version Used', key: 'sourceVersionUsed', width: 25 },
    { header: 'Signature Status', key: 'signatureStatus', width: 20 },
  ]
  procSheet.getRow(1).font = { bold: true }
  procSheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }]

  evidence.procedures.forEach(p => {
    procSheet.addRow({
      subjectIdentifier: safeStr(p.subjectIdentifier),
      visitName: safeStr(p.visitName),
      visitDate: safeStr(p.visitDate),
      procedureName: safeStr(p.procedureName),
      procedureStatus: safeStr(p.procedureStatus),
      performedDate: safeStr(p.performedDate),
      performedBy: safeStr(p.performedBy),
      sourceVersionUsed: safeStr(p.sourceVersionUsed),
      signatureStatus: safeStr(p.signatureStatus),
    })
  })

  // 5. Consent Summary
  const consentSheet = workbook.addWorksheet('Consent Summary')
  consentSheet.columns = [
    { header: 'Subject Identifier', key: 'subjectIdentifier', width: 20 },
    { header: 'Current Consent Status', key: 'currentConsentStatus', width: 25 },
    { header: 'Consent Version', key: 'consentVersion', width: 20 },
    { header: 'IRB Approval Date', key: 'irbApprovalDate', width: 20 },
    { header: 'Site Implementation Date', key: 'siteImplementationDate', width: 25 },
    { header: 'Subject Signed Date', key: 'subjectSignedDate', width: 25 },
    { header: 'Staff Signed Date', key: 'staffSignedDate', width: 20 },
    { header: 'Reconsent Required', key: 'reconsentRequired', width: 20 },
    { header: 'Withdrawn', key: 'withdrawn', width: 15 },
  ]
  consentSheet.getRow(1).font = { bold: true }
  consentSheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }]

  evidence.consents.forEach(c => {
    consentSheet.addRow({
      subjectIdentifier: safeStr(c.subjectIdentifier),
      currentConsentStatus: safeStr(c.currentConsentStatus),
      consentVersion: safeStr(c.consentVersion),
      irbApprovalDate: safeStr(c.irbApprovalDate),
      siteImplementationDate: safeStr(c.siteImplementationDate),
      subjectSignedDate: safeStr(c.subjectSignedDate),
      staffSignedDate: safeStr(c.staffSignedDate),
      reconsentRequired: c.reconsentRequired ? 'Yes' : 'No',
      withdrawn: c.withdrawn ? 'Yes' : 'No',
    })
  })

  // 6. Signature Summary
  const sigSheet = workbook.addWorksheet('Signature Summary')
  sigSheet.columns = [
    { header: 'Subject Identifier', key: 'subjectIdentifier', width: 20 },
    { header: 'Visit Name', key: 'visitName', width: 25 },
    { header: 'Procedure Name', key: 'procedureName', width: 30 },
    { header: 'Signature Type', key: 'signatureType', width: 20 },
    { header: 'Signature Meaning', key: 'signatureMeaning', width: 30 },
    { header: 'Signer Role', key: 'signerRole', width: 20 },
    { header: 'Signed At', key: 'signedAt', width: 20 },
    { header: 'Artifact Hash', key: 'artifactHash', width: 65 },
    { header: 'Status', key: 'status', width: 15 },
  ]
  sigSheet.getRow(1).font = { bold: true }
  sigSheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }]

  evidence.signatures.forEach(s => {
    sigSheet.addRow({
      subjectIdentifier: safeStr(s.subjectIdentifier),
      visitName: safeStr(s.visitName),
      procedureName: safeStr(s.procedureName),
      signatureType: safeStr(s.signatureType),
      signatureMeaning: safeStr(s.signatureMeaning),
      signerRole: safeStr(s.signerRole),
      signedAt: safeStr(s.signedAt),
      artifactHash: safeStr(s.artifactHash),
      status: safeStr(s.status),
    })
  })

  // 7. Document Lineage Summary
  const docSheet = workbook.addWorksheet('Document Lineage Summary')
  docSheet.columns = [
    { header: 'Subject Identifier', key: 'subjectIdentifier', width: 20 },
    { header: 'Visit Name', key: 'visitName', width: 25 },
    { header: 'Procedure Name', key: 'procedureName', width: 30 },
    { header: 'Document Type', key: 'documentType', width: 20 },
    { header: 'Current Version', key: 'currentVersion', width: 20 },
    { header: 'Version Used During Execution', key: 'versionUsed', width: 28 },
    { header: 'Source Package Version', key: 'sourcePackageVersion', width: 22 },
    { header: 'Effective Date', key: 'effectiveDate', width: 20 },
    { header: 'Execution Date', key: 'executionDate', width: 20 },
    { header: 'Uploaded At', key: 'uploadedAt', width: 20 },
    { header: 'Uploaded By', key: 'uploadedBy', width: 20 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Prior Versions Count', key: 'priorVersionsCount', width: 25 },
  ]
  docSheet.getRow(1).font = { bold: true }
  docSheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }]

  evidence.documents.forEach(d => {
    docSheet.addRow({
      subjectIdentifier: safeStr(d.subjectIdentifier),
      visitName: safeStr(d.visitName),
      procedureName: safeStr(d.procedureName),
      documentType: safeStr(d.documentType),
      currentVersion: safeStr(d.currentVersion),
      versionUsed: safeStr(d.versionUsed),
      sourcePackageVersion: safeStr(d.sourcePackageVersion),
      effectiveDate: safeStr(d.effectiveDate),
      executionDate: safeStr(d.executionDate),
      uploadedAt: safeStr(d.uploadedAt),
      uploadedBy: safeStr(d.uploadedBy),
      status: safeStr(d.status),
      priorVersionsCount: safeStr(d.priorVersionsCount),
    })
  })

  const buffer = await workbook.xlsx.writeBuffer()
  return Buffer.from(buffer)
}
