/**
 * Canonical operational_events.event_type registry (Phase 1C).
 * Append-only chronology — never store workflow state here.
 *
 * TS-emitted types use SCREAMING_SNAKE_CASE.
 * Legacy RPC/calendar rows may use other casings until backfilled.
 */

export const OPERATIONAL_EVENT_TYPES = {
  // —— Visit execution ——
  VISIT_CHECKED_IN: 'VISIT_CHECKED_IN',
  VISIT_RESCHEDULED: 'VISIT_RESCHEDULED',
  VISIT_COMPLETED: 'VISIT_COMPLETED',
  VISIT_LOCKED: 'VISIT_LOCKED',

  // —— Procedure execution ——
  PROCEDURE_COMPLETED: 'PROCEDURE_COMPLETED',
  PROCEDURE_SIGNED: 'PROCEDURE_SIGNED',
  PROCEDURE_REOPENED: 'PROCEDURE_REOPENED',
  CONDITIONAL_PROCEDURE_INSTANTIATED: 'CONDITIONAL_PROCEDURE_INSTANTIATED',
  VALIDATION_EXECUTED: 'VALIDATION_EXECUTED',
  SECTION_DISABLED: 'SECTION_DISABLED',
  SECTION_ENABLED: 'SECTION_ENABLED',
  FIELD_LOCKED: 'FIELD_LOCKED',
  FIELD_UNLOCKED: 'FIELD_UNLOCKED',
  NOTE_ADDED: 'NOTE_ADDED',
  PDF_GENERATED: 'PDF_GENERATED',

  // —— Visit closeout ——
  COORDINATOR_SIGNED: 'COORDINATOR_SIGNED',
  INVESTIGATOR_SIGNED: 'INVESTIGATOR_SIGNED',
  CLOSEOUT_REOPENED: 'CLOSEOUT_REOPENED',

  // —— Source / eSource ——
  SOURCE_PACKAGE_PUBLISHED: 'SOURCE_PACKAGE_PUBLISHED',
  SOURCE_RESPONSE_SET_SUBMITTED: 'SOURCE_RESPONSE_SET_SUBMITTED',
  SOURCE_RESPONSE_CORRECTED: 'SOURCE_RESPONSE_CORRECTED',
  SOURCE_RESPONSE_ADDENDUM_ADDED: 'SOURCE_RESPONSE_ADDENDUM_ADDED',
  SOURCE_VALIDATION_FINDING_CREATED: 'SOURCE_VALIDATION_FINDING_CREATED',
  SOURCE_VALIDATION_FINDING_ACKNOWLEDGED: 'SOURCE_VALIDATION_FINDING_ACKNOWLEDGED',
  SOURCE_VALIDATION_FINDING_RESOLVED: 'SOURCE_VALIDATION_FINDING_RESOLVED',
  SOURCE_VALIDATION_FINDING_WAIVED: 'SOURCE_VALIDATION_FINDING_WAIVED',

  // —— Workflow ——
  QUERY_CREATED: 'QUERY_CREATED',
  QUERY_RESOLVED: 'QUERY_RESOLVED',
  SIGNATURE_REQUESTED: 'SIGNATURE_REQUESTED',
  FOLLOW_UP_CREATED: 'FOLLOW_UP_CREATED',

  // —— Pilot compliance guardrails (Phase 16A-2.5) ——
  TEMPORAL_CONSISTENCY_EVALUATED: 'TEMPORAL_CONSISTENCY_EVALUATED',
  BREAK_GLASS_ACCESS_REQUESTED: 'BREAK_GLASS_ACCESS_REQUESTED',
  BREAK_GLASS_EXPIRED_ACCESS_ATTEMPT: 'BREAK_GLASS_EXPIRED_ACCESS_ATTEMPT',
  DELEGATION_RUNTIME_CHECKED: 'DELEGATION_RUNTIME_CHECKED',

  // —— Pilot audit integrity guardrails (Phase 16A-2.6) ——
  SOURCE_FIELD_SNAPSHOT_CAPTURED: 'SOURCE_FIELD_SNAPSHOT_CAPTURED',
  SOURCE_INTEGRITY_VIOLATION_DETECTED: 'SOURCE_INTEGRITY_VIOLATION_DETECTED',
  WORKFLOW_STALE_ALERT: 'WORKFLOW_STALE_ALERT',
  ROLE_CONFLICT_DETECTED: 'ROLE_CONFLICT_DETECTED',

  // —— Runtime automation (Phase 9; coordinator-supervised) ——
  RUNTIME_AUTOMATION_PROPOSED: 'RUNTIME_AUTOMATION_PROPOSED',
  RUNTIME_AUTOMATION_APPLIED: 'RUNTIME_AUTOMATION_APPLIED',
  RUNTIME_AUTOMATION_REVERSED: 'RUNTIME_AUTOMATION_REVERSED',
  RUNTIME_AUTOMATION_OVERRIDDEN: 'RUNTIME_AUTOMATION_OVERRIDDEN',

  // —— Subject lifecycle ——
  SUBJECT_COMPLETED: 'SUBJECT_COMPLETED',
  SUBJECT_WITHDRAWN: 'SUBJECT_WITHDRAWN',
  SUBJECT_SCREEN_FAILED: 'SUBJECT_SCREEN_FAILED',
  SUBJECT_LOST_TO_FOLLOW_UP: 'SUBJECT_LOST_TO_FOLLOW_UP',
  SCHEDULE_MATERIALIZED: 'SCHEDULE_MATERIALIZED',
  PROTOCOL_GRAPH_PUBLISHED: 'PROTOCOL_GRAPH_PUBLISHED',
  /** @deprecated DB/RPC legacy rows may use snake_case; normalize via normalizeOperationalEventType */
  EXTERNAL_RANDOMIZATION_RECORDED: 'external_randomization_recorded',
  /** @deprecated DB/RPC legacy rows may use snake_case; normalize via normalizeOperationalEventType */
  EXTERNAL_RANDOMIZATION_VOIDED: 'external_randomization_voided',

  // —— Safety (spine bridge from profile registry) ——
  ADVERSE_EVENT_CREATED: 'ADVERSE_EVENT_CREATED',
  ADVERSE_EVENT_UPDATED: 'ADVERSE_EVENT_UPDATED',

  // —— Source engine telemetry (append-only diagnostics) ——
  ENGINE_SNAPSHOT_GENERATED: 'ENGINE_SNAPSHOT_GENERATED',
  ENGINE_SNAPSHOT_FAILED: 'ENGINE_SNAPSHOT_FAILED',
  ENGINE_SIGNATURE_BLOCKED: 'ENGINE_SIGNATURE_BLOCKED',
  ENGINE_SIGNATURE_GATE_FAILED_CLOSED: 'ENGINE_SIGNATURE_GATE_FAILED_CLOSED',
  ENGINE_TASKS_MATERIALIZED: 'ENGINE_TASKS_MATERIALIZED',
  ENGINE_TASK_MATERIALIZATION_SKIPPED: 'ENGINE_TASK_MATERIALIZATION_SKIPPED',
  ENGINE_FALLBACK_TEMPLATE_USED: 'ENGINE_FALLBACK_TEMPLATE_USED',
  ENGINE_RUNTIME_STATE_APPLIED: 'ENGINE_RUNTIME_STATE_APPLIED',

  /** Staging pilot binding telemetry (Phase 10E); not coordinator workflow state. */
  PHASE10E_BLINDED_SAFE_SOURCE_REBOUND: 'PHASE10E_BLINDED_SAFE_SOURCE_REBOUND',
  PHASE10E_MINIMAL_BLINDED_SOURCE_BOUND: 'PHASE10E_MINIMAL_BLINDED_SOURCE_BOUND',

  // —— Diagnostics ——
  VPI_LOAD_TELEMETRY: 'VPI_LOAD_TELEMETRY',
} as const

export type OperationalEventType =
  (typeof OPERATIONAL_EVENT_TYPES)[keyof typeof OPERATIONAL_EVENT_TYPES]

/** Types emitted from application code (gateway), not only RPC. */
export const GATEWAY_EMITTED_EVENT_TYPES = new Set<string>([
  OPERATIONAL_EVENT_TYPES.VISIT_CHECKED_IN,
  OPERATIONAL_EVENT_TYPES.VISIT_RESCHEDULED,
  OPERATIONAL_EVENT_TYPES.SOURCE_PACKAGE_PUBLISHED,
  OPERATIONAL_EVENT_TYPES.ADVERSE_EVENT_CREATED,
  OPERATIONAL_EVENT_TYPES.ADVERSE_EVENT_UPDATED,
  OPERATIONAL_EVENT_TYPES.SCHEDULE_MATERIALIZED,
  OPERATIONAL_EVENT_TYPES.PROTOCOL_GRAPH_PUBLISHED,
  OPERATIONAL_EVENT_TYPES.RUNTIME_AUTOMATION_PROPOSED,
  OPERATIONAL_EVENT_TYPES.RUNTIME_AUTOMATION_APPLIED,
  OPERATIONAL_EVENT_TYPES.RUNTIME_AUTOMATION_REVERSED,
  OPERATIONAL_EVENT_TYPES.RUNTIME_AUTOMATION_OVERRIDDEN,
  OPERATIONAL_EVENT_TYPES.TEMPORAL_CONSISTENCY_EVALUATED,
  OPERATIONAL_EVENT_TYPES.BREAK_GLASS_ACCESS_REQUESTED,
  OPERATIONAL_EVENT_TYPES.BREAK_GLASS_EXPIRED_ACCESS_ATTEMPT,
  OPERATIONAL_EVENT_TYPES.DELEGATION_RUNTIME_CHECKED,
  OPERATIONAL_EVENT_TYPES.SOURCE_FIELD_SNAPSHOT_CAPTURED,
  OPERATIONAL_EVENT_TYPES.SOURCE_INTEGRITY_VIOLATION_DETECTED,
  OPERATIONAL_EVENT_TYPES.WORKFLOW_STALE_ALERT,
  OPERATIONAL_EVENT_TYPES.ROLE_CONFLICT_DETECTED,
])

/** Types commonly produced by Postgres RPCs (reference for chronology loaders). */
export const RPC_EMITTED_EVENT_TYPES = new Set<string>([
  OPERATIONAL_EVENT_TYPES.PROCEDURE_COMPLETED,
  OPERATIONAL_EVENT_TYPES.VISIT_COMPLETED,
  OPERATIONAL_EVENT_TYPES.VISIT_LOCKED,
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_SET_SUBMITTED,
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_CORRECTED,
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_ADDENDUM_ADDED,
  OPERATIONAL_EVENT_TYPES.SOURCE_VALIDATION_FINDING_CREATED,
  OPERATIONAL_EVENT_TYPES.SOURCE_VALIDATION_FINDING_ACKNOWLEDGED,
  OPERATIONAL_EVENT_TYPES.SOURCE_VALIDATION_FINDING_RESOLVED,
  OPERATIONAL_EVENT_TYPES.SOURCE_VALIDATION_FINDING_WAIVED,
  OPERATIONAL_EVENT_TYPES.CONDITIONAL_PROCEDURE_INSTANTIATED,
  OPERATIONAL_EVENT_TYPES.COORDINATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.INVESTIGATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.CLOSEOUT_REOPENED,
])

export const ALL_REGISTERED_OPERATIONAL_EVENT_TYPES = new Set<string>([
  ...Object.values(OPERATIONAL_EVENT_TYPES),
])

/** Visit closeout UI labels derived from operational_events. */
export const CLOSEOUT_CHRONOLOGY_TYPES = new Set<string>([
  OPERATIONAL_EVENT_TYPES.COORDINATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.INVESTIGATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.CLOSEOUT_REOPENED,
  OPERATIONAL_EVENT_TYPES.NOTE_ADDED,
])

export const CLOSEOUT_EVENT_LABELS: Record<string, string> = {
  [OPERATIONAL_EVENT_TYPES.NOTE_ADDED]: 'Progress note saved',
  [OPERATIONAL_EVENT_TYPES.COORDINATOR_SIGNED]: 'Coordinator signed',
  [OPERATIONAL_EVENT_TYPES.INVESTIGATOR_SIGNED]: 'Investigator signed',
  [OPERATIONAL_EVENT_TYPES.CLOSEOUT_REOPENED]: 'Closeout reopened',
}
