/**
 * Canonical operational_events.event_type values.
 * Append-only chronology — never store workflow state here.
 */

export const OPERATIONAL_EVENT_TYPES = {
  PROCEDURE_SIGNED: 'PROCEDURE_SIGNED',
  PROCEDURE_REOPENED: 'PROCEDURE_REOPENED',
  VALIDATION_EXECUTED: 'VALIDATION_EXECUTED',
  SECTION_DISABLED: 'SECTION_DISABLED',
  SECTION_ENABLED: 'SECTION_ENABLED',
  FIELD_LOCKED: 'FIELD_LOCKED',
  FIELD_UNLOCKED: 'FIELD_UNLOCKED',
  NOTE_ADDED: 'NOTE_ADDED',
  PDF_GENERATED: 'PDF_GENERATED',
  QUERY_CREATED: 'QUERY_CREATED',
  QUERY_RESOLVED: 'QUERY_RESOLVED',
  SIGNATURE_REQUESTED: 'SIGNATURE_REQUESTED',
  FOLLOW_UP_CREATED: 'FOLLOW_UP_CREATED',
  COORDINATOR_SIGNED: 'COORDINATOR_SIGNED',
  INVESTIGATOR_SIGNED: 'INVESTIGATOR_SIGNED',
  CLOSEOUT_REOPENED: 'CLOSEOUT_REOPENED',
  SUBJECT_COMPLETED: 'SUBJECT_COMPLETED',
  SUBJECT_WITHDRAWN: 'SUBJECT_WITHDRAWN',
  SUBJECT_SCREEN_FAILED: 'SUBJECT_SCREEN_FAILED',
  SUBJECT_LOST_TO_FOLLOW_UP: 'SUBJECT_LOST_TO_FOLLOW_UP',
  /** Phase 11D: coordinator confirmed conditional procedure map. */
  CONDITIONAL_PROCEDURE_INSTANTIATED: 'CONDITIONAL_PROCEDURE_INSTANTIATED',
  /** VPI read-layer exceeded performance budget (append-only diagnostic). */
  VPI_LOAD_TELEMETRY: 'VPI_LOAD_TELEMETRY',
} as const

export type OperationalEventType =
  (typeof OPERATIONAL_EVENT_TYPES)[keyof typeof OPERATIONAL_EVENT_TYPES]

/** Visit closeout UI labels derived from operational_events. */
export const CLOSEOUT_CHRONOLOGY_TYPES = new Set<string>([
  OPERATIONAL_EVENT_TYPES.COORDINATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.INVESTIGATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.CLOSEOUT_REOPENED,
  OPERATIONAL_EVENT_TYPES.NOTE_ADDED,
])

export const CLOSEOUT_EVENT_LABELS: Record<string, string> = {
  [OPERATIONAL_EVENT_TYPES.NOTE_ADDED]: 'Progress note saved',
  [OPERATIONAL_EVENT_TYPES.COORDINATOR_SIGNED]: 'Coordinator signed',
  [OPERATIONAL_EVENT_TYPES.INVESTIGATOR_SIGNED]: 'Investigator signed',
  [OPERATIONAL_EVENT_TYPES.CLOSEOUT_REOPENED]: 'Closeout reopened',
}
