import { VIPPolicyOutput } from "../vip-policy/vip-policy-types";

export const mockPolicyOutputsForPI: VIPPolicyOutput[] = [
  {
    // 1. Abnormal AST
    severity: "CRITICAL",
    policy_basis: ["SUBJECT_SAFETY"],
    enforcement_level: "WARNING",
    authority_boundary: "REQUIRE_PI_REVIEW",
    actionability: "NON_ACTIONABLE_MEDICAL_BOUNDARY",
    signal_source: "LAB_PORTAL",
    evidence_status: "COMPLETE",
    ui_actions: ["REQUIRE_ADJUDICATION"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: [],
    override_policy: { override_allowed: false, override_roles_allowed: [], override_requires_reason: true, override_requires_signature: true, override_requires_second_reviewer: false, override_expires_after_hours: null },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "PI",
    escalation_due_within_hours: 24,
    confidence_band: "HIGH",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: new Date().toISOString(),
    engine_version: "v1",
    reason: "Abnormal AST Level (145 U/L) requires medical significance assessment.",
    uncertainty_note: ""
  },
  {
    // 2. Abnormal ECG
    severity: "CRITICAL",
    policy_basis: ["SUBJECT_SAFETY"],
    enforcement_level: "WARNING",
    authority_boundary: "REQUIRE_PI_REVIEW",
    actionability: "NON_ACTIONABLE_MEDICAL_BOUNDARY",
    signal_source: "SOURCE_DOC",
    evidence_status: "COMPLETE",
    ui_actions: ["REQUIRE_ADJUDICATION"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: [],
    override_policy: { override_allowed: false, override_roles_allowed: [], override_requires_reason: true, override_requires_signature: true, override_requires_second_reviewer: false, override_expires_after_hours: null },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "PI",
    escalation_due_within_hours: 24,
    confidence_band: "HIGH",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: new Date().toISOString(),
    engine_version: "v1",
    reason: "QTc Prolongation detected (465 ms).",
    uncertainty_note: ""
  },
  {
    // 3. Eligibility criterion medically ambiguous
    severity: "HIGH",
    policy_basis: ["ELIGIBILITY"],
    enforcement_level: "WARNING",
    authority_boundary: "REQUIRE_PI_REVIEW",
    actionability: "NON_ACTIONABLE_MEDICAL_BOUNDARY",
    signal_source: "EDC",
    evidence_status: "COMPLETE",
    ui_actions: ["REQUIRE_ADJUDICATION"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: [],
    override_policy: { override_allowed: false, override_roles_allowed: [], override_requires_reason: true, override_requires_signature: true, override_requires_second_reviewer: false, override_expires_after_hours: null },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "PI",
    escalation_due_within_hours: 48,
    confidence_band: "MEDIUM",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: new Date().toISOString(),
    engine_version: "v1",
    reason: "Prior medical history involves uncontrolled hypertension. Requires explicit clearance.",
    uncertainty_note: ""
  },
  {
    // 4. AE causality review
    severity: "HIGH",
    policy_basis: ["SUBJECT_SAFETY"],
    enforcement_level: "WARNING",
    authority_boundary: "REQUIRE_PI_REVIEW",
    actionability: "NON_ACTIONABLE_MEDICAL_BOUNDARY",
    signal_source: "SOURCE_DOC",
    evidence_status: "COMPLETE",
    ui_actions: ["REQUIRE_ADJUDICATION"],
    required_evidence: [],
    allowed_actions: [],
    forbidden_actions: [],
    override_policy: { override_allowed: false, override_roles_allowed: [], override_requires_reason: true, override_requires_signature: true, override_requires_second_reviewer: false, override_expires_after_hours: null },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "PI",
    escalation_due_within_hours: 72,
    confidence_band: "HIGH",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: new Date().toISOString(),
    engine_version: "v1",
    reason: "New adverse event (Headache) requires causality and severity assessment.",
    uncertainty_note: ""
  },
  {
    // 5. Pregnancy test missing (Should NOT appear in PI Inbox)
    severity: "HARD_STOP",
    policy_basis: ["ELIGIBILITY"],
    enforcement_level: "HARD_STOP",
    authority_boundary: "SITE_CAN_ACT", // Because it just requires the coordinator to do it
    actionability: "ACTIONABLE",
    signal_source: "EDC",
    evidence_status: "MISSING",
    ui_actions: ["HARD_STOP_ACTION"],
    required_evidence: ["Serum Pregnancy Test Result"],
    allowed_actions: [],
    forbidden_actions: ["Randomize"],
    override_policy: { override_allowed: false, override_roles_allowed: [], override_requires_reason: false, override_requires_signature: false, override_requires_second_reviewer: false, override_expires_after_hours: null },
    audit_log_fields: {},
    financial_certainty: "KNOWN",
    escalation_target: "CRC",
    escalation_due_within_hours: 0,
    confidence_band: "EXPERT",
    policy_version: "2.0",
    pattern_version: "1.0",
    evaluation_timestamp: new Date().toISOString(),
    engine_version: "v1",
    reason: "WOCBP requires negative pregnancy test prior to IP administration.",
    uncertainty_note: ""
  }
];
