import { OPERATIONAL_EVENT_TYPES } from '@/lib/operations/event-types'

/** Event types commonly used in visit replay segments. */
export const VISIT_REPLAY_EVENT_TYPES = [
  OPERATIONAL_EVENT_TYPES.VISIT_CHECKED_IN,
  OPERATIONAL_EVENT_TYPES.VISIT_RESCHEDULED,
  OPERATIONAL_EVENT_TYPES.VISIT_COMPLETED,
  OPERATIONAL_EVENT_TYPES.VISIT_LOCKED,
  OPERATIONAL_EVENT_TYPES.PROCEDURE_COMPLETED,
  OPERATIONAL_EVENT_TYPES.PROCEDURE_SIGNED,
  OPERATIONAL_EVENT_TYPES.CONDITIONAL_PROCEDURE_INSTANTIATED,
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_SET_SUBMITTED,
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_CORRECTED,
  OPERATIONAL_EVENT_TYPES.SOURCE_VALIDATION_FINDING_CREATED,
  OPERATIONAL_EVENT_TYPES.SOURCE_VALIDATION_FINDING_RESOLVED,
  OPERATIONAL_EVENT_TYPES.ADVERSE_EVENT_CREATED,
  OPERATIONAL_EVENT_TYPES.ADVERSE_EVENT_UPDATED,
  OPERATIONAL_EVENT_TYPES.QUERY_CREATED,
  OPERATIONAL_EVENT_TYPES.QUERY_RESOLVED,
  OPERATIONAL_EVENT_TYPES.COORDINATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.INVESTIGATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.PROTOCOL_GRAPH_PUBLISHED,
] as const

export const SAFETY_EVENT_TYPES = [
  OPERATIONAL_EVENT_TYPES.ADVERSE_EVENT_CREATED,
  OPERATIONAL_EVENT_TYPES.ADVERSE_EVENT_UPDATED,
] as const

export const SOURCE_SIGNATURE_EVENT_TYPES = [
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_SET_SUBMITTED,
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_CORRECTED,
  OPERATIONAL_EVENT_TYPES.SOURCE_RESPONSE_ADDENDUM_ADDED,
  OPERATIONAL_EVENT_TYPES.PROCEDURE_SIGNED,
  OPERATIONAL_EVENT_TYPES.COORDINATOR_SIGNED,
  OPERATIONAL_EVENT_TYPES.INVESTIGATOR_SIGNED,
] as const
