export const DELEGATION_LOG_COLUMNS = [
  'Task/Responsibility',
  'Name of Delegatee',
  'Title/Role',
  'Initials',
  'Date Delegated',
  'Date Started',
  'Date Ended',
  'Delegatee Signature',
  'PI Signature',
  'PI Initials',
] as const

export const DELEGATION_TASKS = [
  'Obtain Informed Consent',
  'Subject Screening and Enrollment',
  'Subject Identification and Recruitment',
  'Product Dispensing',
  'IP Accountability',
  'IP Storage and Temperature Monitoring',
  'SAE/SUSAR Reporting',
  'CRF/eCRF Completion',
  'Source Data Documentation',
  'Lab Sample Collection and Shipping',
  'Randomization',
  'Unblinding Procedures',
  'Medical Assessments',
  'Vital Signs Measurement',
  'Blood Draw/Phlebotomy',
  'Adverse Event Monitoring',
  'Concomitant Medication Recording',
  'Patient Diary Collection',
  'Follow-up Calls',
  'Query Resolution',
] as const

export const TRAINING_LOG_COLUMNS = [
  'Trainee Name',
  'Title/Role',
  'Initials',
  'Training Date',
  'Training Topic',
  'Training Type',
  'Instructor Name',
  'Instructor Initials',
  'Certificate Attached',
  'Certificate Number',
  'Trainee Signature',
  'Instructor Signature',
  'Notes/Comments',
] as const

export const TRAINING_TYPES = [
  'In-Person',
  'Remote/Teleconference',
  'Video Conference',
  'E-Learning/Online',
  'On-the-Job Training',
  'Refresher Training',
  'Protocol-Specific Training',
  'Initial Training',
] as const

export const TRAINING_TOPICS = [
  'ICH-GCP Certification',
  'Protocol-Specific Training',
  'Protocol Amendments',
  'Informed Consent Process',
  'Investigational Product Handling',
  'IP Dispensing Procedures',
  'IP Accountability and Storage',
  'Temperature Monitoring and Logging',
  'SAE/SUSAR Reporting Procedures',
  'Adverse Event Documentation',
  'CRF/eCRF Completion Guidelines',
  'Source Data Documentation',
  'Laboratory Sample Collection and Shipping',
  'Laboratory Reference Ranges',
  'Randomization Procedures',
  'Unblinding Procedures',
  'EDC System Training',
  'Patient Diary Management',
  'Medical Equipment Usage',
  'Vital Signs Measurement',
  'Phlebotomy Procedures',
  'Study-Specific Procedures',
  'Regulatory Requirements',
  'IRB/CEIC Communication',
  'Monitoring Visit Procedures',
  'Study Closure Procedures',
] as const

export const DELEGATION_EXAMPLE_ROWS = [
  [
    'Obtain Informed Consent',
    'Maria Lopez',
    'Research Coordinator',
    'ML',
    '05/01/2026',
    '05/02/2026',
    '',
    'ML',
    'LZ',
    'LZ',
  ],
  [
    'Medical Assessments',
    'Luis Zepeda',
    'Principal Investigator',
    'LZ',
    '05/01/2026',
    '05/01/2026',
    '',
    'LZ',
    'LZ',
    'LZ',
  ],
  [
    'IP Accountability',
    'Ana Rivera',
    'Pharmacist',
    'AR',
    '05/03/2026',
    '05/03/2026',
    '',
    'AR',
    'LZ',
    'LZ',
  ],
  [
    'Query Resolution',
    'Daniel Kim',
    'Data Coordinator',
    'DK',
    '05/04/2026',
    '05/04/2026',
    '',
    'DK',
    'LZ',
    'LZ',
  ],
] as const

export const TRAINING_EXAMPLE_ROWS = [
  [
    'Maria Lopez',
    'Research Coordinator',
    'ML',
    '05/01/2026',
    'Protocol-Specific Training',
    'Video Conference',
    'Luis Zepeda',
    'LZ',
    'No',
    '',
    'ML',
    'LZ',
    'Initial protocol training completed before delegated tasks.',
  ],
  [
    'Ana Rivera',
    'Pharmacist',
    'AR',
    '05/03/2026',
    'IP Accountability and Storage',
    'In-Person',
    'Luis Zepeda',
    'LZ',
    'Yes',
    'CERT-IP-001',
    'AR',
    'LZ',
    'Certificate filed in Training Documentation.',
  ],
  [
    'Daniel Kim',
    'Data Coordinator',
    'DK',
    '05/04/2026',
    'EDC System Training',
    'E-Learning/Online',
    'Sponsor Portal',
    'SP',
    'Yes',
    'EDC-2026-014',
    'DK',
    'SP',
    'System access granted after completion.',
  ],
] as const

export const DELEGATION_USAGE_INSTRUCTIONS = [
  'The PI remains responsible for all assigned study tasks, even when delegated.',
  'Staff must be qualified and trained before delegated duties begin.',
  'Delegatee and PI signatures or initials must be completed before assigned tasks start.',
  'Use the same initials that appear in research records.',
  'Maintain this as a living document and update it when staffing or roles change.',
  'Update the log within 5 business days of any personnel or responsibility change.',
  'Start a new row when staff leave the study or materially change roles.',
] as const

export const TRAINING_USAGE_INSTRUCTIONS = [
  'Document training immediately upon completion, not retroactively.',
  'When a formal completion certificate exists, file the certificate as evidence and reference it here.',
  'The trainee signs to confirm completion.',
  'The instructor signs to confirm delivery of the training.',
  'Maintain this as a living document and update it with each new training event.',
  'Update the log within 5 business days of training completion.',
  'Include refresher training when required.',
  'Record training for all staff involved in the study.',
] as const
