import { MedicalAuthorityRule } from "./medical-authority-types";

export const defaultMedicalAuthorityRules: MedicalAuthorityRule[] = [
  {
    rule_id: "AUTH_VITALS",
    procedure_type: "VITALS",
    procedure_category: "CLINICAL_ASSESSMENT",
    study_specific: false,
    protocol_specific: false,
    performer_roles: ["CRC", "RN", "MA", "SUB_INVESTIGATOR", "PI"],
    reviewer_roles: ["CRC", "RN", "SUB_INVESTIGATOR", "PI"],
    adjudicator_roles: ["SUB_INVESTIGATOR", "PI"],
    signatory_roles: ["CRC", "RN", "MA", "SUB_INVESTIGATOR", "PI"],
    override_roles: ["PI"],
    oversight_required: false,
    oversight_level: "OPERATIONAL",
    blind_scope: "ANY",
    delegation_required: true,
    training_required: true,
    pi_review_required: false,
    si_review_allowed: true,
    medical_monitor_required: false,
    sponsor_required: false,
    central_lab_required: false,
    hard_stop_if_missing: false,
    policy_basis: ["CRITICAL_DATA_INTEGRITY"],
    description: "Vital signs collection and operational review."
  },
  {
    rule_id: "AUTH_ELIGIBILITY",
    procedure_type: "ELIGIBILITY_REVIEW",
    procedure_category: "CLINICAL_ASSESSMENT",
    study_specific: false,
    protocol_specific: true,
    performer_roles: ["SUB_INVESTIGATOR", "PI"],
    reviewer_roles: ["PI"],
    adjudicator_roles: ["PI"],
    signatory_roles: ["SUB_INVESTIGATOR", "PI"],
    override_roles: ["PI"],
    oversight_required: true,
    oversight_level: "CRITICAL_MEDICAL",
    blind_scope: "ANY",
    delegation_required: true,
    training_required: true,
    pi_review_required: true, // PI must sign off eligibility ultimately
    si_review_allowed: true,
    medical_monitor_required: false,
    sponsor_required: false,
    central_lab_required: false,
    hard_stop_if_missing: true,
    policy_basis: ["ELIGIBILITY"],
    description: "Final determination of subject eligibility."
  },
  {
    rule_id: "AUTH_LAB_REVIEW",
    procedure_type: "LAB_REVIEW",
    procedure_category: "LABORATORY",
    study_specific: false,
    protocol_specific: false,
    performer_roles: ["CRC", "RN"], // CRC can log the lab
    reviewer_roles: ["SUB_INVESTIGATOR", "PI"],
    adjudicator_roles: ["PI", "SUB_INVESTIGATOR"], // CS/NCS
    signatory_roles: ["PI", "SUB_INVESTIGATOR"],
    override_roles: ["PI"],
    oversight_required: true,
    oversight_level: "MEDICAL",
    blind_scope: "ANY",
    delegation_required: true,
    training_required: false,
    pi_review_required: false,
    si_review_allowed: true,
    medical_monitor_required: false,
    sponsor_required: false,
    central_lab_required: false,
    hard_stop_if_missing: true,
    policy_basis: ["SUBJECT_SAFETY"],
    description: "Clinical significance review of lab results."
  },
  {
    rule_id: "AUTH_SAE_REVIEW",
    procedure_type: "SAE_REVIEW",
    procedure_category: "SAFETY",
    study_specific: false,
    protocol_specific: false,
    performer_roles: ["PI"], // Only PI can determine causality for SAEs initially
    reviewer_roles: ["PI", "MEDICAL_MONITOR", "SPONSOR"],
    adjudicator_roles: ["PI"],
    signatory_roles: ["PI"],
    override_roles: [], // No override for SAEs locally
    oversight_required: true,
    oversight_level: "SAFETY_CRITICAL",
    blind_scope: "ANY",
    delegation_required: true,
    training_required: true,
    pi_review_required: true,
    si_review_allowed: false, // SAE is strictly PI
    medical_monitor_required: true,
    sponsor_required: true,
    central_lab_required: false,
    hard_stop_if_missing: true,
    policy_basis: ["SUBJECT_SAFETY"],
    description: "Serious Adverse Event review and causality determination."
  },
  {
    rule_id: "AUTH_UNBLINDED_IP",
    procedure_type: "UNBLINDED_IP_REVIEW",
    procedure_category: "PHARMACY",
    study_specific: false,
    protocol_specific: false,
    performer_roles: ["UNBLINDED_PHARMACIST"],
    reviewer_roles: ["UNBLINDED_PHARMACIST"],
    adjudicator_roles: ["UNBLINDED_PHARMACIST", "SPONSOR"],
    signatory_roles: ["UNBLINDED_PHARMACIST"],
    override_roles: [],
    oversight_required: true,
    oversight_level: "CRITICAL_MEDICAL",
    blind_scope: "UNBLINDED",
    delegation_required: true,
    training_required: true,
    pi_review_required: false, // PI is typically blinded
    si_review_allowed: false,
    medical_monitor_required: false,
    sponsor_required: false,
    central_lab_required: false,
    hard_stop_if_missing: true,
    policy_basis: ["BLINDING_PROTECTION"],
    description: "Viewing or reviewing unblinded investigational product allocations."
  },
  {
    rule_id: "AUTH_WAIVER_APPROVAL",
    procedure_type: "WAIVER_APPROVAL",
    procedure_category: "REGULATORY",
    study_specific: false,
    protocol_specific: true,
    performer_roles: ["PI", "MEDICAL_MONITOR", "SPONSOR"],
    reviewer_roles: ["SPONSOR", "MEDICAL_MONITOR"],
    adjudicator_roles: ["SPONSOR", "MEDICAL_MONITOR"],
    signatory_roles: ["PI", "SPONSOR"],
    override_roles: [],
    oversight_required: true,
    oversight_level: "SAFETY_CRITICAL",
    blind_scope: "ANY",
    delegation_required: true,
    training_required: true,
    pi_review_required: true,
    si_review_allowed: false,
    medical_monitor_required: true,
    sponsor_required: true,
    central_lab_required: false,
    hard_stop_if_missing: true,
    policy_basis: ["SUBJECT_SAFETY", "ELIGIBILITY"],
    description: "Protocol waiver or exemption approval."
  }
];
